POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MzU2MjA3NDcsInVzZXJJZCI6MX0.Td-LXO4b-klkys7mSW38U0jAzw1zZ3tLMfadGazcNoI

{
    "Name": "Test new event",
    "Description": "Test event!!!",
    "Location": "A test location",
    "DateTime": "2025-01-01T15:30:00.000Z"    
}
