POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzM1NjE0MzE5LCJ1c2VySWQiOjJ9.ac6If0mOxnrnfDYWnk95O_fiVDv4un8o6PT0pyVo4eQ

{
    "Name": "Test event",
    "Description": "Test event!!!",
    "Location": "A test location",
    "DateTime": "2025-01-01T15:30:00.000Z"    
}
