DELETE http://localhost:8080/events/3
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzM1NjE3ODc0LCJ1c2VySWQiOjJ9.xSXdyGCKmUKzt31-vgkGVhwV1I8iZAFlCUKf9IYnnU8